In [1]:
import pandas as pd

In [8]:
info={
    "Name": ["Ankit","Sonu","Master"],
     "Marks":[300,320,350]
 }
df=pd.DataFrame(info)

In [9]:
df

     Name  Marks
0   Ankit    300
1    Sonu    320
2  Master    350

In [21]:
#01.Series:--->
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[0])
print(s[4])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
1
5

In [14]:
s=pd.Series([20,22,24,26] ,index=["Ankit","Sonu","Master","Ram"])
print(s)
print(s["Ankit"])
print(s["Sonu"])
print(s.index)

Ankit     20
Sonu      22
Master    24
Ram       26
dtype: int64
20
22
Index(['Ankit', 'Sonu', 'Master', 'Ram'], dtype='object')

In [19]:
#vectorized operations
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([6,7,8,9,10])
print(s1 + s2)

#mutable value
s1[2]=300
print(s1)

changed_s1=s1.drop(4)     #dropping the value 
print(changed_s1)

0     7
1     9
2    11
3    13
4    15
dtype: int64
0      1
1      2
2    300
3      4
4      5
dtype: int64
0      1
1      2
2    300
3      4
dtype: int64

In [24]:
#02.DataFrame:--->
#creating the DataFrame through dictionary of list
info={
    "Name": ["Ankit","Sonu","Master"],
    "Marks":[300,320,350],
    "Age":[20,22,24]
 }
df=pd.DataFrame(info)
print(df)
print(type(df))

print(df.index)  #labels of rows
print(df.columns)   #to access the columns values

     Name  Marks  Age
0   Ankit    300   20
1    Sonu    320   22
2  Master    350   24
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Age'], dtype='object')

In [30]:
#creating the DataFrame through list of lists
df=pd.DataFrame([["Ankit",20],["Sonu",22],["Master",24]],columns=["Name","Age"])
print(df)

     Name  Age
0   Ankit   20
1    Sonu   22
2  Master   24

In [35]:
#creating the DataFrame through numpy array
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [44]:
#usage of CSV and JSON files
df=pd.read_csv("Employee_data.csv")
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [42]:
#df=pd.read_json("Employee_data.json")
#df

In [50]:
#DataFrame Methods
df.head()
#df.head(2)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [51]:
df.tail()
#df.tail(2)

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [52]:
df.sample()
#df.sample(4)

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [54]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [55]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [57]:
df.shape

(10, 5)

In [59]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [65]:
df["Age"].dtype
#df["columns_name"].dtype

dtype('int64')