In [35]:
import pandas as pd

In [36]:
df=pd.read_csv("raw_data.csv")

In [37]:
#Handling the missing data
df.isnull()  #true for null val(NaN)
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [38]:
df.isnull().sum()     # counts missing vals per column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [39]:
df.dropna()            # drops rows with missing values
df.dropna(axis=1)      # drops cols with missing values

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [40]:
df.fillna(0)   # fills NaN with value

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [41]:
age_mean=df["age"].mean()               # fills column with mean
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]=cleaned_data["age"].fillna(age_mean)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [42]:
df.ffill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  29.0  Canada   Female  62000.0
3    3          Alex  29.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  47000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6        Li Wei  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0   India     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  29.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA     Male  58000.0

In [43]:
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [44]:
#Handle the duplicates
df.duplicated()  #True for duplicated rows

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [45]:
df.duplicated("country")  #True for duplicated rows in particular col

0     False
1      True
2     False
3      True
4     False
5     False
6     False
7     False
8      True
9     False
10     True
dtype: bool

In [46]:
df.duplicated(["country","gender"])

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [47]:
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [48]:
#Handle the data types 
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [49]:
df2=df.copy()
df2=df2.fillna(0)
df2["age"]=df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [50]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [51]:
#Handle the string
df["gender"].str.lower()

0        male
1        male
2      female
3     unknown
4      female
5        male
6      female
7        male
8      female
9        male
10        NaN
Name: gender, dtype: object

In [52]:
df["gender"].str.upper()

0        MALE
1        MALE
2      FEMALE
3     UNKNOWN
4      FEMALE
5        MALE
6      FEMALE
7        MALE
8      FEMALE
9        MALE
10        NaN
Name: gender, dtype: object

In [53]:
df["name"].str.strip()    #removes extra spaces from the beginning and end of each string

0         John Doe
1         John Doe
2       Jane Smith
3             Alex
4     Maria Garcia
5           Li Wei
6              NaN
7       Ahmed Khan
8       Rachel Lee
9      Carlos Ruiz
10     Emily Davis
Name: name, dtype: object

In [54]:
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [55]:
df["name"].str.split(" ")

0         [John, Doe]
1         [John, Doe]
2       [Jane, Smith]
3              [Alex]
4     [Maria, Garcia]
5           [Li, Wei]
6                 NaN
7       [Ahmed, Khan]
8       [Rachel, Lee]
9      [Carlos, Ruiz]
10     [Emily, Davis]
Name: name, dtype: object

In [56]:
df["country"].str.contains("india",case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object

In [57]:
#Transforming the data (Feature Engineering)
#01.copy()
df2=df.copy()
df2["tax"]=df2["income"].apply( lambda x :"20%" if x>55000 else "10%" if x>=40000 else "5%" )
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN   5%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [58]:
#02. map()
gender_val_change= {"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df["gender"].map(gender_val_change)
df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN   5%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%

In [59]:
#03. assign()
df2=df2.assign(new_income=df2["income"] * 1.1)
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   5%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [60]:
#04. replace(old,new)
df2["country"]=df2["country"].replace("India", "Bharat")
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN   5%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0  Bharat      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [61]:
#05. Renaming
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income","Tax","New_Income"]
df2.rename(columns={"Income": "Salary"})
df2.rename(index={0: "first"})

       Id          Name   Age Country Gender   Income  Tax  New_Income
first   1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1       1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN     USA      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN   5%         NaN
5       5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6       6           NaN  45.0  Bharat      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0     USA    NaN  58000.0  20%     63800.0

In [62]:
#05. Sorting
df2.sort_values("Income")                   # sort values in ascending
df2=df2.fillna(50)
# df2.sort_values("Income",ascending=False)   # sort values in descending
sorted_df=df2.sort_values(["Income","Age"])        # sorts for income,if income is same then sorts for age 
sorted_df.sort_index()

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
3    3          Alex  50.0     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F     50.0   5%        50.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6            50  45.0  Bharat      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA     50  58000.0  20%     63800.0

In [64]:
#06. Reset the index
sorted_df.reset_index()
sorted_df.reset_index(drop=True)           # to drop original index vals

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    4  Maria Garcia  34.0   Spain      F     50.0   5%        50.0
1    9   Carlos Ruiz  50.0  Mexico      M  45000.0  10%     49500.0
2    3          Alex  50.0     USA      U  47000.0  10%     51700.0
3    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
4    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
5    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
6   10   Emily Davis  31.0     USA     50  58000.0  20%     63800.0
7    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
8    2    Jane Smith  50.0  Canada      F  62000.0  20%     68200.0
9    7    Ahmed Khan  38.0      50      M  68000.0  20%     74800.0
10   6            50  45.0  Bharat      F  73000.0  20%     80300.0

In [ ]:
#07.Rank
sorted_df["Ranking"]=sorted_df["Income"].rank()
sorted_df["Ranking"]=sorted_df["Income"].rank(ascending=False)  #change the rank from low -> high to high->low
sorted_df

In [ ]:
#08. Reorder
sorted_df[["Id", "Name", "Age", "Gender", "Country", "Income","New_Income","Tax"]]

In [68]:
# Task - shift id column to end
df2=df.copy()
new_col_order=[col for col in df.columns if col!="id"] + ["id"]
df2[new_col_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [82]:
#writing the csv file
df2= df.copy()

df2= df2.drop_duplicates()
df2= df2.fillna(0)

df2= df2.sort_values("income")
df2= df2.reset_index(drop=True)
df2.to_csv("writing to csv file.csv")

In [83]:
df2

   id          name   age country   gender   income
0   4  Maria Garcia  34.0   Spain   Female      0.0
1   9   Carlos Ruiz   0.0  Mexico     Male  45000.0
2   3          Alex   0.0     USA  Unknown  47000.0
3   5        Li Wei  27.0   China     Male  51000.0
4   1      John Doe  29.0     USA     Male  55000.0
5  10   Emily Davis  31.0     USA        0  58000.0
6   2    Jane Smith   0.0  Canada   Female  62000.0
7   8    Rachel Lee  29.0     USA   Female  62000.0
8   7    Ahmed Khan  38.0       0     Male  68000.0
9   6             0  45.0   India   Female  73000.0

In [101]:
#Group & Aggregation of datd
df.groupby("country")["income"].mean()       # mean income for each country
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [91]:
df.groupby("gender")["income"].mean()    # mean income for each gender
df.groupby("gender")["income"].min()

gender
Female     62000.0
Male       45000.0
Unknown    47000.0
Name: income, dtype: float64

In [102]:
df.groupby("country")["income"].count()    # count of gender for each country
df.groupby("gender")["income"].count()

gender
Female     3
Male       5
Unknown    1
Name: income, dtype: int64

In [103]:
df.groupby("country")["income"].agg(["mean","min","max"])                          # applies multiple aggregate functions
df.groupby("country")["income"].agg(avg_sal="mean",min_sal="min",max_sal="max")    # rename aggregate

         avg_sal  min_sal  max_sal
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [104]:
df.groupby("country").agg({              # aggregate on multiple cols
    "age":"mean",
    "income":"mean"
})

          age   income
country
Canada    NaN  62000.0
China    27.0  51000.0
India    45.0  73000.0
Mexico    NaN  45000.0
Spain    34.0      NaN
USA      29.5  55400.0

In [98]:
df.groupby("country").agg({
    "age":"max",
    "income":"mean"
})

          age   income
country
Canada    NaN  62000.0
China    27.0  51000.0
India    45.0  73000.0
Mexico    NaN  45000.0
Spain    34.0      NaN
USA      31.0  55400.0

In [105]:
df.groupby("country").agg(           # rename aggregates on multiple cols
    avg_age=("age","mean"),
    avg_sal=("income","mean")
)

         avg_age  avg_sal
country
Canada       NaN  62000.0
China       27.0  51000.0
India       45.0  73000.0
Mexico       NaN  45000.0
Spain       34.0      NaN
USA         29.5  55400.0

In [132]:
# Melt & Pivot
df3 = pd.DataFrame({
    "country": ["USA", "USA", "India", "India"],
    "year": [2020, 2021, 2020, 2021],
    "sales": [100, 120, 90, 110],
    "profit": [20, 25, 18, 22]
})

melted_df3=df3.melt(
    id_vars=["country", "year"],     # columns to keep
    value_vars=["sales", "profit"],  # columns to unpivot
    var_name="metric",               # new column name for variable
    value_name="value (in Lakhs)"    # new column name for value (default is value)
)

df3

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22

In [133]:
melted_df3

  country  year  metric  value (in Lakhs)
0     USA  2020   sales               100
1     USA  2021   sales               120
2   India  2020   sales                90
3   India  2021   sales               110
4     USA  2020  profit                20
5     USA  2021  profit                25
6   India  2020  profit                18
7   India  2021  profit                22

In [135]:
melted_df3.pivot(
    index=["country", "year"],   # cols that become the NEW row index - can't for just country
    columns="metric",            # col whose unique values will become the cols
    values="value (in Lakhs)"    # col whose values will fill the new df

)

metric        profit  sales
country year
India   2020      18     90
        2021      22    110
USA     2020      20    100
        2021      25    120

In [138]:
# Merging & Joining 
df_customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

pd.merge(df_customers,df_orders,on="customer_id")      #inner join

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [142]:
pd.merge(df_customers,df_orders,on="customer_id",how="left")    #left join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [143]:
pd.merge(df_customers,df_orders,on="customer_id",how="right")          #right joim

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [144]:
pd.merge(df_customers,df_orders,on="customer_id",how="outer")        #outer join

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [114]:
df3

  country  year  sales  profit
0     USA  2020    100      20
1     USA  2021    120      25
2   India  2020     90      18
3   India  2021    110      22